// <auto-generated />
using CodeChallenge1.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeChallenge1.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220322051718_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeChallenge1.Models.Entities.Cup", b =>
                {
                    b.Property<char>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<char>("Id"));

                    b.Property<bool>("HasBall")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Cups");
                });
#pragma warning restore 612, 618
        }
    }
}
